version: "3.9"

services:
  frontend:
    command: sh -c "npm install && npm run dev"
    # Mount source for instant hot-reload on change
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=500
      - CHOKIDAR_USEPOLLING=true

  viz-service:
    command: sh -c "uvicorn server:app --host 0.0.0.0 --port 4006 --reload"
    volumes:
      - ./services/viz:/app
    ports:
      - "4006:4006"

  analysis-service:
    command: sh -c "node --watch server.js"
    volumes:
      - ./services/analysis:/app
    ports:
      - "4004:4004"

  auth-service:
    ports:
      - "4001:4001"

  media-service:
    ports:
      - "4003:4003"

  feed-service:
    ports:
      - "4005:4005"

  llm-service:
    ports:
      - "4007:4007"

  auth-db:
    ports:
      - "5433:5432"

  media-db:
    ports:
      - "5434:5432"

  analysis-db:
    ports:
      - "5436:5432"

  feed-db:
    ports:
      - "5435:5432"

volumes:
  web_node_modules:
