version: "3.9"

services:
  frontend:
    build: ./apps/web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_AUTH=/api/auth
      - NEXT_PUBLIC_API_MEDIA=/api/media
      - NEXT_PUBLIC_API_ANALYSIS=/api/analysis
      - NEXT_PUBLIC_API_FEED=/api/feed
      - NEXT_PUBLIC_API_VIZ=/api/viz
      - NEXT_PUBLIC_API_LLM=/api/llm
    depends_on:
      - auth-service
      - media-service
      - analysis-service
      - feed-service
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  auth-service:
    build: ./services/auth
    environment:
      - NODE_ENV=production
      - PORT=4001
      - DATABASE_URL=postgres://auth_user:auth_pass@auth-db:5432/auth_db
      - JWT_SECRET=dev_jwt_secret_change_me
      - BCRYPT_ROUNDS=10
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
    depends_on:
      - auth-db
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  auth-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_pass
      - POSTGRES_DB=auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  media-service:
    build: ./services/media
    environment:
      - NODE_ENV=production
      - PORT=4003
      - DATABASE_URL=postgres://media_user:media_pass@media-db:5432/media_db
      - MEDIA_MASTER_KEY_BASE64=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
      - AUTH_BASE=http://auth-service:4001
    depends_on:
      - media-db
      - auth-service
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  media-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=media_user
      - POSTGRES_PASSWORD=media_pass
      - POSTGRES_DB=media_db
    volumes:
      - media_db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  analysis-service:
    build: ./services/analysis
    environment:
      - NODE_ENV=production
      - PORT=4004
      - DATABASE_URL=postgres://analysis_user:analysis_pass@analysis-db:5432/analysis_db
      - VIZ_BASE=http://viz-service:4006
      - LLM_SVC=http://llm-service:4007
      - VIZ_USE_HSMM=1
    depends_on:
      - analysis-db
      - llm-service
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  analysis-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=analysis_user
      - POSTGRES_PASSWORD=analysis_pass
      - POSTGRES_DB=analysis_db
    volumes:
      - analysis_db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  feed-service:
    build: ./services/feed
    environment:
      - NODE_ENV=production
      - PORT=4005
      - DATABASE_URL=postgres://feed_user:feed_pass@feed-db:5432/feed_db
      - AUTH_BASE=http://auth-service:4001
    depends_on:
      - feed-db
      - auth-service
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  feed-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=feed_user
      - POSTGRES_PASSWORD=feed_pass
      - POSTGRES_DB=feed_db
    volumes:
      - feed_db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  viz-service:
    build: ./services/viz
    environment:
      - PORT=4006
      - MEDIA_BASE=http://media-service:4003
      - ANALYSIS_BASE=http://analysis-service:4004
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_BASE_URL=${LLM_BASE_URL}
      - LLM_MODEL=${LLM_MODEL}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  llm-service:
    build: ./services/llm
    environment:
      - PORT=4007
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_BASE_URL=${LLM_BASE_URL}
      - LLM_MODEL=${LLM_MODEL}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  auth_db_data:
  media_db_data:
  feed_db_data:
  analysis_db_data:
